services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/demo
      DB_USERNAME: sonia
      DB_PASSWORD: sonia
    ports:
      - "8080:8080"

  db:
    image: postgres:17-alpine
    container_name: demo-db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: sonia
      POSTGRES_PASSWORD: sonia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonia -d demo"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
